// Playground code examples — kept in a plain .ts file to avoid
// nested template literal / JSX parse issues in the main page component.

export const EXAMPLES: Record<string, string> = {
  'Hello World': [
    '// Simple React component with Tailwind',
    'function App() {',
    '  return (',
    '    <div className="flex items-center justify-center h-full">',
    '      <div className="text-center">',
    '        <h1 className="text-4xl font-bold text-blue-600 mb-4">',
    '          Hello, World!',
    '        </h1>',
    '        <p className="text-gray-600 text-lg">',
    '          Edit this code to see live updates',
    '        </p>',
    '      </div>',
    '    </div>',
    '  );',
    '}',
    '',
    'render(<App />);',
  ].join('\n'),

  'Counter (useState)': [
    '// useState hook example',
    'function Counter() {',
    '  const [count, setCount] = React.useState(0);',
    '',
    '  return (',
    '    <div className="flex flex-col items-center justify-center h-full gap-6">',
    '      <h1 className="text-2xl font-bold">Counter Demo</h1>',
    '      <div className="text-6xl font-mono font-bold text-blue-600">',
    '        {count}',
    '      </div>',
    '      <div className="flex gap-3">',
    '        <button',
    '          onClick={() => setCount(c => c - 1)}',
    '          className="px-6 py-2 rounded-lg bg-red-500 text-white font-semibold hover:bg-red-600 transition-colors"',
    '        >',
    '          Decrement',
    '        </button>',
    '        <button',
    '          onClick={() => setCount(0)}',
    '          className="px-6 py-2 rounded-lg bg-gray-200 text-gray-700 font-semibold hover:bg-gray-300 transition-colors"',
    '        >',
    '          Reset',
    '        </button>',
    '        <button',
    '          onClick={() => setCount(c => c + 1)}',
    '          className="px-6 py-2 rounded-lg bg-green-500 text-white font-semibold hover:bg-green-600 transition-colors"',
    '        >',
    '          Increment',
    '        </button>',
    '      </div>',
    '    </div>',
    '  );',
    '}',
    '',
    'render(<Counter />);',
  ].join('\n'),

  'Todo List': [
    '// A full todo list with useState',
    'function TodoApp() {',
    '  const [todos, setTodos] = React.useState([',
    '    { id: 1, text: "Learn React", done: true },',
    '    { id: 2, text: "Learn TypeScript", done: false },',
    '    { id: 3, text: "Build something awesome", done: false },',
    '  ]);',
    '  const [input, setInput] = React.useState(\'\');',
    '',
    '  const addTodo = () => {',
    '    if (!input.trim()) return;',
    '    setTodos([...todos, { id: Date.now(), text: input.trim(), done: false }]);',
    '    setInput(\'\');',
    '  };',
    '',
    '  const toggle = (id) => {',
    '    setTodos(todos.map(t => t.id === id ? { ...t, done: !t.done } : t));',
    '  };',
    '',
    '  const remove = (id) => setTodos(todos.filter(t => t.id !== id));',
    '',
    '  return (',
    '    <div className="max-w-md mx-auto mt-8 p-6">',
    '      <h1 className="text-2xl font-bold mb-6 text-center">My Todos</h1>',
    '      <div className="flex gap-2 mb-4">',
    '        <input',
    '          value={input}',
    '          onChange={e => setInput(e.target.value)}',
    '          onKeyDown={e => e.key === \'Enter\' && addTodo()}',
    '          placeholder="Add a todo..."',
    '          className="flex-1 border border-gray-300 rounded-lg px-3 py-2 text-sm"',
    '        />',
    '        <button onClick={addTodo} className="px-4 py-2 bg-blue-500 text-white rounded-lg text-sm font-medium hover:bg-blue-600">',
    '          Add',
    '        </button>',
    '      </div>',
    '      <ul className="space-y-2">',
    '        {todos.map(todo => (',
    '          <li key={todo.id} className="flex items-center gap-3 p-3 rounded-lg border border-gray-100 hover:bg-gray-50 group">',
    '            <input type="checkbox" checked={todo.done} onChange={() => toggle(todo.id)} className="w-4 h-4" />',
    '            <span className={todo.done ? \'flex-1 text-sm line-through text-gray-400\' : \'flex-1 text-sm\'}>',
    '              {todo.text}',
    '            </span>',
    '            <button onClick={() => remove(todo.id)} className="opacity-0 group-hover:opacity-100 text-red-400 hover:text-red-600 text-xs">',
    '              x',
    '            </button>',
    '          </li>',
    '        ))}',
    '      </ul>',
    '      <p className="text-xs text-gray-400 mt-4 text-center">',
    '        {todos.filter(t => t.done).length} of {todos.length} completed',
    '      </p>',
    '    </div>',
    '  );',
    '}',
    '',
    'render(<TodoApp />);',
  ].join('\n'),

  'Card Component': [
    '// Reusable card with badge component',
    'function Badge({ children, color = \'blue\' }) {',
    '  const colors = {',
    '    blue: \'bg-blue-100 text-blue-700\',',
    '    green: \'bg-green-100 text-green-700\',',
    '    yellow: \'bg-yellow-100 text-yellow-700\',',
    '  };',
    '  return (',
    '    <span className={"px-2 py-0.5 rounded-full text-xs font-medium " + colors[color]}>',
    '      {children}',
    '    </span>',
    '  );',
    '}',
    '',
    'function Card({ title, description, tags, status }) {',
    '  const statusColor = status === \'Done\' ? \'green\' : status === \'In Progress\' ? \'blue\' : \'yellow\';',
    '  return (',
    '    <div className="rounded-xl border border-gray-200 p-5 bg-white shadow-sm hover:shadow-md transition-shadow">',
    '      <div className="flex items-start justify-between mb-3">',
    '        <h3 className="font-semibold text-gray-900">{title}</h3>',
    '        <Badge color={statusColor}>{status}</Badge>',
    '      </div>',
    '      <p className="text-sm text-gray-500 mb-4">{description}</p>',
    '      <div className="flex gap-2 flex-wrap">',
    '        {tags.map(t => <Badge key={t}>{t}</Badge>)}',
    '      </div>',
    '    </div>',
    '  );',
    '}',
    '',
    'function App() {',
    '  const cards = [',
    '    { title: \'Build auth system\', description: \'Login and sessions with BetterAuth.\', tags: [\'auth\', \'next.js\'], status: \'Done\' },',
    '    { title: \'Add Prisma ORM\', description: \'Database schema and PostgreSQL.\', tags: [\'prisma\', \'db\'], status: \'In Progress\' },',
    '    { title: \'Set up PostHog\', description: \'Analytics and feature flags.\', tags: [\'analytics\'], status: \'Todo\' },',
    '  ];',
    '  return (',
    '    <div className="p-6 space-y-3 max-w-md mx-auto">',
    '      <h1 className="font-bold text-lg mb-4">Project Board</h1>',
    '      {cards.map(c => <Card key={c.title} {...c} />)}',
    '    </div>',
    '  );',
    '}',
    '',
    'render(<App />);',
  ].join('\n'),
};
